### ISSUE TITLE
libgcc_s_dw2-1.dll is missing

### ISSUE THREAD

**Issue by JSkrat** [pornel/jpeg-compressor#4]
i tried to run it, but it says 'missing dll'
can you please recompile it
http://forums.codeblocks.org/index.php?topic=16728.0
here i found solution for codeblocks, at bottom

**Comment by pornel** [comment]
Sorry, I can't rebuild it as I don't have Windows. #1

The binary is out of date anyway. You're better off using [mozjpeg](https://imageoptim.com/mozjpeg/) now.

**Comment by JSkrat** [comment]
anyway thanks
