### ISSUE TITLE
Incompatibility with mozjpeg

### ISSUE THREAD

**Issue by sunnybear** [pornel/jpeg-compressor#7]
Hello. Thank you for great utility. I have troubles with batch optimization of files after mozjpeg scans.
For example (attached) after
/opt/mozjpeg/bin/jpegtran -copy none -optimize -progressive -outfile "out.jpg" "initial.jpg"
![initial](https://cloud.githubusercontent.com/assets/304569/15955825/015c7498-2eed-11e6-983f-88f47c56f5c8.jpg)

encoder gives an error Failed loading file "out.jpg". But the resulted file from mozjpeg is OK:
identify: out.jpg JPEG 655x432 655x432+0+0 8-bit DirectClass 93.8KB 0.000u 0:00.000

Compiled the latest version for git, CentOS 6, 64 bit

mozjpeg latest, also from git (compiled 7th, June).

**Comment by pornel** [comment]
If you feed a file from mozjpeg to this compressor, it will undo all of mozjpeg's work and make the file larger and look worse.
